kind: Service
apiVersion: v1
metadata:
  name: catering-quote-service
spec:
  type: NodePort
  selector:
    app: catering-quote
  ports:
  - protocol: TCP
    port: 80
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catering-quote-deployment
  labels:
    app: catering-quote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catering-quote
  template:
    metadata:
      labels:
        app: catering-quote
    spec:
      containers:
      - name: catering-quote
        image: rajeev74/catering-quote:latest
        ports:
        - containerPort: 80
        livenessProbe:
              httpGet:
                path: /healthcheck
                port: 80
              initialDelaySeconds: 10
              periodSeconds: 3