apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*/apache2/access.log
      fields:
        type: apache_access
      fields_under_root: true
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    - type: log
      enabled: true
      paths:
        - /var/log/*/apache2/error.log
      fields:
        type: apache_error
      fields_under_root: true
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    - type: log
      enabled: true
      paths:
        - /var/lib/docker/containers/*/*.log
      fields:
        type: docker_syslog
      fields_under_root: true
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: log
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    output.logstash:
      hosts: ["es.stage.avonindiangrill.com:5044"]
      bulk_max_size: 1024
---