kind: Service
apiVersion: v1
metadata:
  name: catering-quote-service
spec:
  type: LoadBalancer
  selector:
    app: catering-quote
  ports:
  - protocol: TCP
    port: 80
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catering-quote-deployment
  labels:
    app: catering-quote
spec:
  replicas: 4
  selector:
    matchLabels:
      app: catering-quote
  template:
    metadata:
      labels:
        app: catering-quote
    spec:
      containers:
        - name: catering-quote
          image: rajeev74/catering-quote:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /var/log/
              name: log
              subPath: docker/$(POD_NAME)
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          ports:
          - containerPort: 80
      volumes:
        - name: log
          hostPath:
            # directory location on host
            path: /var/log/
            # this field is optional
            type: Directory
