apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*/apache2/access.log
      fields:
        type: apache_access
      fields_under_root: true
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    - type: log
      enabled: true
      paths:
        - /var/log/*/apache2/error.log
      fields:
        type: apache_error
      fields_under_root: true
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    - type: log
      enabled: true
      paths:
        - /var/lib/docker/containers/*/*.log
      fields:
        type: docker_syslog
      fields_under_root: true
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: log
      processors:
      - add_kubernetes_metadata:
        in_cluster: true
    output.logstash:
      hosts: ["es.stage.avonindiangrill.com:5044"]
      bulk_max_size: 1024
---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.4.1
        args: [
          "-c","/etc/filebeat/filebeat.yml",
          "-e",
        ]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat
          readOnly: true
        - name: log
          mountPath: /var/log/
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: log
        hostPath:
          # directory location on host
          path: /var/log/docker/
          # this field is optional
          type: Directory
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        emptyDir: {}

---