apiVersion: rbac.authorization.k8s.io/v1
kind: KubernetesRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: KubernetesRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---


